#!/bin/sh
# Caution, must be kept compatible with dash used by some Linux distros.

UNAME=`uname -s | tr '[A-Z]' '[a-z]'`
DIRNAME=`dirname "$0"`

# DIRNAME may not be in the toolchain directory if this script was symlinked.
# try to find the symlink target
which readlink >/dev/null 2>&1 && readlink "$0" >/dev/null 2>&1 && {
    SYMLINK=`readlink "$0"`

    # On MacOS X, the readlink command hasn't the same behavior than the others operating systems based on Unix.
    if [ "$UNAME" == "darwin" ]; then
    	DIRNAME=`dirname "$SYMLINK"`
    else
    	DIRNAME="$SYMLINK"/..
    fi
}

# Cygwin owns a dedicated command to find the symlink target
if [ "$UNAME" = "cygwin" ]; then
	DIRNAME=`cygpath --path --windows "$DIRNAME"`
fi

NORMALGCC=`which nspire-gcc`
NDLESSDIR=`dirname "$NORMALGCC"`
# DIRNAME may not be in the toolchain directory if this script was symlinked.
# try to find the symlink target
which readlink >/dev/null 2>&1 && readlink "$NORMALGCC" >/dev/null 2>&1 && {
    NDLESSDIR=`readlink "$NORMALGCC"`

    # On MacOS X, the readlink command hasn't the same behavior than the others operating systems based on Unix.
    if [ "$UNAME" == "darwin" ]; then
    	NDLESSDIR=`dirname "$SYMLINK"`
    else
    	NDLESSDIR="$SYMLINK"/..
    fi
}

if [ "$UNAME" = "cygwin" ]; then
	NDLESSDIR=`cygpath --path --windows "$DIRNAME"`
fi

GCC=`(which arm-elf-gcc arm-none-eabi-gcc arm-linux-gnueabi-gcc | head -1) 2>/dev/null`
"$GCC" -Wl,-elf2flt -nostdlib -T "$DIRNAME/ldscript" -L "$NDLESSDIR/../lib" -static "$DIRNAME/crt0.o" "$@" -lndls
